/*-------------------------EXEMPLOS DE FUNCOES-------------------------------*/
SELECT LTRIM('   OLÁ') AS RESULTADO;

SELECT RTRIM('OLÁ   ') AS RESULTADO;

SELECT TRIM('     OLÁ   ') AS RESULTADO;

SELECT CONCAT('OLÁ', ' ', 'TUDO BEM', '?') AS RESULTADO;

SELECT UPPER('olá, tudo bem?') AS RESULTADO;

SELECT SUBSTRING('OLÁ, TUDO BEM?', 6) AS RESULTADO;

SELECT SUBSTRING('OLÁ, TUDO BEM?', 6, 4) AS RESULTADO;

SELECT CONCAT(NOME, ' (', CPF, ') ') AS RESULTADO FROM tabela_de_clientes;

SELECT CURDATE();

SELECT CURRENT_TIME();

SELECT CURRENT_TIMESTAMP();

SELECT YEAR(current_timestamp());

SELECT DAY(current_timestamp());

SELECT MONTH(CURRENT_TIMESTAMP());

SELECT MONTHNAME(current_timestamp());

SELECT DATEDIFF(CURRENT_TIMESTAMP(), '2021-01-01') AS RESULTADO;

SELECT DATEDIFF(CURRENT_TIMESTAMP(), '1996-11-09') AS RESULTADO;

SELECT CURRENT_TIMESTAMP() AS DIA_HOJE, DATE_SUB(current_timestamp(), INTERVAL 5 DAY) AS RESULTADO; 

SELECT DISTINCT DATA_VENDA, DAYNAME(DATA_VENDA) AS DIA, MONTHNAME(DATA_VENDA) AS MES, YEAR(DATA_VENDA) AS ANO FROM notas_fiscais;

SELECT (23+((25-2)/2) * 45) AS RESULTADO;

SELECT CEILING(12.33333333233233) AS RESULTADO;

SELECT ROUND(12.33333333233233) AS RESULTADO;

SELECT FLOOR(12.33333333233233) AS RESULTADO;

SELECT RAND() AS RESULTADO;

SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE * PRECO, 2) AS FATURAMENTO FROM itens_notas_fiscais;

/*------------CONVERSÃO DE TIPOS--------------------*/
SELECT CONCAT('O dia de hoje é: ', CURRENT_TIMESTAMP()) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(), '%d/%m/%Y')) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(), '%W, %d/%m/%Y')) AS RESULTADO;

SELECT CONCAT('O dia de hoje é: ', 
DATE_FORMAT(CURRENT_TIMESTAMP(), '%W, %d/%m/%Y - %U')) AS RESULTADO;

SELECT CONVERT(23.3, CHAR) AS RESULTADO;
SELECT SUBSTRING(CONVERT(23.3, CHAR),1,1) AS RESULTADO;